project:
  type: website
  output-dir: docs

website:
  sidebar:
    logo: "assets/img/ivy_logo.png"
    background: "#43AE43"
    foreground: "#ffffff"
    border: true
    collapse-level: 2
    contents: 
      - auto: "*unify_existing_code/"
      - auto: "*temp_demos/"
