project:
  type: website
  output-dir: docs

listing:
  template: assets/ejs/gallery.ejs

website:
  navbar:
    logo: "assets/img/ivy_logo.png"
    logo-alt: "Ivy Demos"
    background: "#43AE43"
    foreground: "#ffffff"
  
  sidebar:
    border: true
    collapse-level: 2
    contents: 
      - auto: "*unify_existing_code/"
      - auto: "*temp_demos/"
