name: gcp-auth-script
on:
  push:
    branches:
      - test
      - main
      - release/* #ToDo: add a release branch
  pull_request:
  workflow_dispatch:

jobs:
  test-auth:
     runs-on: ubuntu-latest
     steps:
       - id: 'auth'
         uses: 'google-github-actions/auth@v0.4.0'
         with:
           credentials_json: '${{ secrets.GCP_AUTH }}'

       - name: 'Set up Cloud SDK'
         uses: 'google-github-actions/setup-gcloud@v1'
         with:
           version: '>= 363.0.0'

       - name: 'Use gcloud CLI'
         run: 'gcloud compute instances start test-instance'