name: test-basics
on: [push, pull_request, workflow_dispatch]

jobs:
  Ubuntu:
    strategy:
      matrix:
        modules: [ 01_write_ivy_code, 02_unify_code, 03_compile_code, 04_transpile_code, 05_lazy_vs_eager, 06_how_to_use_decorators, 07_transpile_any_library, 08_transpile_any_model, 09_write_a_model_using_ivy ]

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Demos🛎
        uses: actions/checkout@v2
        with:
          path: demos
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Set Short Job Name
        id: preprocess
        run: echo "::set-output name=short_name::${{ matrix.modules/^[0-9]+_(.*)$/\1/ }}"

      - name: Run Demo Testing
        id: tests
        run: |
          cd demos
          docker run -v `pwd`:/ivy/demos unifyai/ivy:latest demos/tests/test_demos.sh ${{ secrets.USER_API_KEY }} ${{ matrix.modules }}.ipynb "basics"

      - name: Check on Failures
        if: steps.tests.outcome != 'success'
        run: exit 1

      # Construct the job name using the preprocessed short name
      - name: Post-process Job Name
        run:
        echo "Job name: ${{ job.jobname }} / ${{ steps.preprocess.outputs.short_name }}"
