name: test-basics
on: [push, pull_request, workflow_dispatch]

jobs:
  SetupDocker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Demos🛎
        uses: actions/checkout@v2
        with:
          path: demos
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Set Up Docker Container
        id: setup-docker
        run: |
          cd demos
          docker run -d --name ivy-container unifyai/ivy:latest tail -f /dev/null

  RunTests:
    needs: SetupDocker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Demos🛎
        uses: actions/checkout@v2
        with:
          path: demos
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Run Demo Testing
        id: tests
        run: |
          cd demos
          docker exec ivy-container /ivy/demos/tests/test_demos.sh ${{ secrets.USER_API_KEY }} ${{ matrix.test_files }} "basics"

      - name: Check on Failures
        if: steps.tests.outcome != 'success'
        run: exit 1

    strategy:
      matrix:
        include:
          - test_files: "01_write_ivy_code.ipynb"
          - test_files: "02_unify_code.ipynb"
          - test_files: "03_compile_code.ipynb"
          # Add more test files here
